apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Poojass1998/gitops-infra.git   # <-- updated with your repo
    path: k8s                                                 # <-- watches the k8s folder
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

